# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main }

    App\Admin\PageAdmin:
        arguments: [~, App\Entity\Page, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Pagina }
    App\Admin\AgendaAdmin:
        arguments: [~, App\Entity\Agenda, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Agenda }
    App\Admin\NavigationAdmin:
        arguments: [~, App\Entity\Navigation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Navigatie }
    App\Admin\CompetitionGalleryAdmin:
        arguments: [~, App\Entity\CompetitionGallery, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Competities }
    App\Admin\GalleryAdmin:
        arguments: [~, App\Entity\Gallery, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Galerijen }
    App\Admin\ImageAdmin:
        arguments: [~, App\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Fotos }
    App\Admin\MemberAdmin:
        arguments: [~, App\Entity\Member, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Leden }

    sonata.admin.competition_images:
        class: App\Admin\CompetitionImageAdmin
        arguments: [~, App\Entity\CompetitionImage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Competitie Images, show_in_dashboard: false }