easy_admin:
    site_name: 'Fotoclub Uitgeest beheer'
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - 'admin/form.html.twig'
    entities:
        Gallery:
            class: App\Entity\Gallery
            list:
                fields:
                    - 'id'
                    - 'name'
                    - 'description'
                    - 'member.name'
            edit:
                fields:
                    - 'name'
                    - 'description'
                    - 'active'
                    - 'member'
                    - 'dateCreated'
                    - 'dateChanged'
                    - 'images'
        CompetitionGallery:
            class: App\Entity\CompetitionGallery
            edit:
                fields:
                    - 'name'
                    - 'description'
                    - 'dateCreated'
                    - 'active'
                    - { property: 'images', label: 'Images', type: 'collection', type_options: { entry_type: 'App\Form\CompetitionImages', by_reference: false, block_name: 'competition_images' } }
        Image:
            class: App\Entity\Image
        Member:
            class: App\Entity\Member
        Navigation:
            class: App\Entity\Navigation
            form:
                fields:
                    - 'title'
                    - { property: 'pages', label: 'Paginas', type_options: { by_reference: false } }
        Page:
            class: App\Entity\Page
            list:
                fields:
                    - 'title'
                    - 'dateCreated'
                    - 'enabled'
                    - 'homepage'
            form:
                fields:
                    - 'title'
                    - 'text'
                    - 'enabled'
                    - 'navigation'
                    - 'homepage'