easy_admin:
    entities:
        Gallery:
            class: App\Entity\Gallery
            list:
                fields:
                    - 'id'
                    - 'name'
                    - 'description'
                    - 'member.name'
            edit:
                fields:
                    - 'name'
                    - 'description'
                    - 'active'
                    - 'member'
                    - 'dateCreated'
                    - 'dateChanged'
                    - 'images'
        CompetitionGallery:
            class: App\Entity\CompetitionGallery
            edit:
                fields:
                    - {property: 'images', sortable: true}
                sort: ['images.sort_order', 'ASC']
        Image:
            class: App\Entity\Image
        Member:
            class: App\Entity\Member
