easy_admin:
    entities:
        Gallery:
            class: App\Entity\Gallery
            list:
                fields:
                    - 'id'
                    - 'name'
                    - 'description'
                    - 'member.name'
            edit:
                fields:
                    - 'name'
                    - 'description'
                    - 'active'
                    - 'member'
                    - 'dateCreated'
                    - 'dateChanged'
                    - 'images'

        Image:
            class: App\Entity\Image
        Member:
            class: App\Entity\Member
