easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Galerij
        - App\Entity\Images
        - App\Entity\Items
        - App\Entity\Leden
        - App\Entity\Users
