framework:
    router:
        strict_requirements: ~
        utf8: true

cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        persistence:
            orm:
                enabled: true